# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yomi/Cmake/bigproject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yomi/Cmake/bigproject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yomi/Cmake/bigproject/CMakeFiles /home/yomi/Cmake/bigproject//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yomi/Cmake/bigproject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project

# Build rule for target.
project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project
.PHONY : project

# fast build rule for target.
project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/build
.PHONY : project/fast

lex.o: lex.cpp.o
.PHONY : lex.o

# target to build an object file
lex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/lex.cpp.o
.PHONY : lex.cpp.o

lex.i: lex.cpp.i
.PHONY : lex.i

# target to preprocess a source file
lex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/lex.cpp.i
.PHONY : lex.cpp.i

lex.s: lex.cpp.s
.PHONY : lex.s

# target to generate assembly for a file
lex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/lex.cpp.s
.PHONY : lex.cpp.s

order/create.o: order/create.cpp.o
.PHONY : order/create.o

# target to build an object file
order/create.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/order/create.cpp.o
.PHONY : order/create.cpp.o

order/create.i: order/create.cpp.i
.PHONY : order/create.i

# target to preprocess a source file
order/create.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/order/create.cpp.i
.PHONY : order/create.cpp.i

order/create.s: order/create.cpp.s
.PHONY : order/create.s

# target to generate assembly for a file
order/create.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/order/create.cpp.s
.PHONY : order/create.cpp.s

order/delete.o: order/delete.cpp.o
.PHONY : order/delete.o

# target to build an object file
order/delete.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/order/delete.cpp.o
.PHONY : order/delete.cpp.o

order/delete.i: order/delete.cpp.i
.PHONY : order/delete.i

# target to preprocess a source file
order/delete.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/order/delete.cpp.i
.PHONY : order/delete.cpp.i

order/delete.s: order/delete.cpp.s
.PHONY : order/delete.s

# target to generate assembly for a file
order/delete.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/order/delete.cpp.s
.PHONY : order/delete.cpp.s

order/order.o: order/order.cpp.o
.PHONY : order/order.o

# target to build an object file
order/order.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/order/order.cpp.o
.PHONY : order/order.cpp.o

order/order.i: order/order.cpp.i
.PHONY : order/order.i

# target to preprocess a source file
order/order.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/order/order.cpp.i
.PHONY : order/order.cpp.i

order/order.s: order/order.cpp.s
.PHONY : order/order.s

# target to generate assembly for a file
order/order.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/order/order.cpp.s
.PHONY : order/order.cpp.s

order/select.o: order/select.cpp.o
.PHONY : order/select.o

# target to build an object file
order/select.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/order/select.cpp.o
.PHONY : order/select.cpp.o

order/select.i: order/select.cpp.i
.PHONY : order/select.i

# target to preprocess a source file
order/select.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/order/select.cpp.i
.PHONY : order/select.cpp.i

order/select.s: order/select.cpp.s
.PHONY : order/select.s

# target to generate assembly for a file
order/select.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/order/select.cpp.s
.PHONY : order/select.cpp.s

order/update.o: order/update.cpp.o
.PHONY : order/update.o

# target to build an object file
order/update.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/order/update.cpp.o
.PHONY : order/update.cpp.o

order/update.i: order/update.cpp.i
.PHONY : order/update.i

# target to preprocess a source file
order/update.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/order/update.cpp.i
.PHONY : order/update.cpp.i

order/update.s: order/update.cpp.s
.PHONY : order/update.s

# target to generate assembly for a file
order/update.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/order/update.cpp.s
.PHONY : order/update.cpp.s

project.o: project.cpp.o
.PHONY : project.o

# target to build an object file
project.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/project.cpp.o
.PHONY : project.cpp.o

project.i: project.cpp.i
.PHONY : project.i

# target to preprocess a source file
project.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/project.cpp.i
.PHONY : project.cpp.i

project.s: project.cpp.s
.PHONY : project.s

# target to generate assembly for a file
project.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/project.cpp.s
.PHONY : project.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... project"
	@echo "... lex.o"
	@echo "... lex.i"
	@echo "... lex.s"
	@echo "... order/create.o"
	@echo "... order/create.i"
	@echo "... order/create.s"
	@echo "... order/delete.o"
	@echo "... order/delete.i"
	@echo "... order/delete.s"
	@echo "... order/order.o"
	@echo "... order/order.i"
	@echo "... order/order.s"
	@echo "... order/select.o"
	@echo "... order/select.i"
	@echo "... order/select.s"
	@echo "... order/update.o"
	@echo "... order/update.i"
	@echo "... order/update.s"
	@echo "... project.o"
	@echo "... project.i"
	@echo "... project.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

